# Generated by Django 5.2.17 on 2026-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_pushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='android', max_length=20, unique=True)),
                ('minimum_version', models.CharField(help_text="Bu versiyadan PASTKI versiyalar majburiy yangilashga yo'naltiriladi. Masalan: 1.2.0", max_length=20)),
                ('latest_version', models.CharField(help_text="Play Store'dagi eng oxirgi versiya raqami", max_length=20)),
                ('update_message', models.TextField(blank=True, default='Ilovaning yangi versiyasi chiqdi! Davom etish uchun yangilang.')),
                ('store_url', models.URLField(blank=True, default='https://play.google.com/store/apps/details?id=com.murod999.posmobile')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
